* autohotkey
This is my personal AutoHotkey configuration / script. It implements the following:

** Alt Drag to move windows
Hold ALT, click anywhere inside a window, and move the mouse to drag the window around, similar to what is available in Linux. This is based on [[https://www.howtogeek.com/howto/windows-vista/get-the-linux-altwindow-drag-functionality-in-windows][this article from HowToGeek]], but adds handling of maximized windows: the original code ignores maximizes window, while this script unmaximizes the window, moves it to the position of the mouse, and then allows for dragging. I have removed the option of using ESC to cancel the drag operation, as I've been using this for years and never even noticed it was there until I looked more closely at the code now.

** Change window transparency
With the following shortcuts:

- Win + O: toggles between opaque and 50% transparent window
- Win + Mouse Wheel up / down: gradually increases / decreases transparency

This is based on [[https://www.howtogeek.com/howto/44915/how-to-change-window-transparency-in-windows-7/][another article from HowToGeek]], but I've rewritten most of it to play around with AutoHotkey scripting. The main behavior difference is that in the original, Win+O only turns off transparency, it does not toggle it. I've also made it so that transparency does not wrap-around when you use the Mouse Wheel to go beyond fully transparent, and removed a debug shortcut (Win+G) which doesn't belong in a finished script.
